name: pitchscope
description: Flutter Android pitch training app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔐 Permissions
  permission_handler: ^12.0.1

  # 📁 File access
  path_provider: ^2.1.3

  # 🎤 Mic pitch detection
  record: ^6.2.0

  # 🎵 Device songs
  on_audio_query: ^2.9.0

  # 🎵 Play song
  just_audio: ^0.9.36

  # 🎧 Audio session
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/songs/Bhairavi_ragam.mp3
    - assets/pitch/

# ✅ ADD THIS
dependency_overrides:
  on_audio_query_android:
    path: local_plugins/on_audio_query_android